spring:
  application:
    name: sleep-parser
  profiles:
    active: default

server:
  port: 8021

logging:
  level:
    com.leanstar.sleepparser: info
    org.springframework: warn
  config: classpath:logback-plus.xml

mqtt:
  broker: ${MQTT_BROKER:tcp://192.168.10.188:1883}
  client:
    id: ${MQTT_CLIENT_ID:sleep-parser-server}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
